### ISSUE TITLE
Doesn't work with local file opened with file:// protocole.

### ISSUE THREAD

**Issue by msankhala** [DataTables/VisualEvent#27]
Visual Event 2 doesn't work with local files opened with file:/// protocole while Visual Event 1 work well with file:// protocole.

**Comment by nowherenearithaca** [comment]
btw - I think with newer security restrictions in chrome, you can get cross origin errors for some files when using VisualEvent with the file protocol

<img width="585" alt="screen shot 2018-06-16 at 1 57 56 am" src="https://user-images.githubusercontent.com/1015962/41496506-623eabc6-710f-11e8-880a-53b5768d5767.png">
