### ISSUE TITLE
Refused to load the script 'https://www.sprymedia.co.uk/VisualEvent/VisualEvent_Loader.js?rand=1422735185563' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://ajax.googleapis.com".

### ISSUE THREAD

**Issue by cprcrack** [DataTables/VisualEvent#57]
I get this error on the console when running Visual Event 2. Can you provide a fully inline Javascript that doesn't load anything from such domain? Thanks.

**Comment by DataTables** [comment]
Can you tell me what bowser you are using and what page you are using where this error occurs please? There are some cases where the browser stops Visual Event from loading external scripts due to their configured security policies - there is more or less nothing Visual Event can do about that.

**Comment by cprcrack** [comment]
Chrome 40, web.whatsapp.com. If you could provide the whole script as one inline piece of Javascript code without external paths, it would probably work.

**Comment by DataTables** [comment]
Great thanks for the additional information. Visual Event (particularly if jQuery needs to be included) is got to result in one seriously large bookmark entry as a single script. I don't really want to make a public release of that, but it would be quote possibly just to grab the [source file](https://sprymedia.co.uk/VisualEvent/builds/VisualEvent-1398853496/js/VisualEvent-jQuery.js) and dump it into your own bookmark.
