### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by valtido** [DataTables/VisualEvent#62]
Your website sprymedia is down.

**Comment by tkuijer** [comment]
Can confirm, same for me. DNS server doesn't respond.

```
$ dig any sprymedia.co.uk

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> any sprymedia.co.uk
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by valtido** [comment]
I think, it would be best, if it hosted on a CDN, when users are using the script, that way if the owner decides not to continue hosting it, at least there will be a legacy somewhere on a CDN which will remove the coupling/dependency to that particular domain name.

**Comment by valtido** [comment]
it's back up and running

**Comment by DataTables** [comment]
Yup - sorry. I had some maintenance to do on the server yesterday and it was placed behind a router that wasn't letting UDP/53 traffic through annoyingly. I was resolved a little while ago.

However, yes, it needs to go onto a CDN!
